// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/mfmadarang/fhir-interop/internal/store"
)

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PatientConnection struct {
	Edges    []*PatientEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type PatientEdge struct {
	Node   *store.PatientRecord `json:"node"`
	Cursor string               `json:"cursor"`
}

type Query struct {
}
