type Patient {
  id: ID!
  familyName: String
  givenName: String
  gender: String
  birthDate: String
}

type Encounter {
  id: ID!
  patientId: String
  status: String
  periodStart: String
  periodEnd: String
}

type Observation {
  id: ID!
  patientId: String
  encounterId: String
  status: String
  codeSystem: String
  codeValue: String
  effectiveDateTime: String
}

type Query {
  patient(id: ID!): Patient
  patients(first: Int = 20, after: String): PatientConnection!
  encountersByPatient(patientId: ID!): [Encounter!]!
  observationsByPatient(patientId: ID!): [Observation!]!
}

type PatientEdge {
  node: Patient!
  cursor: String!
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: String
}

type PatientConnection {
  edges: [PatientEdge!]!
  pageInfo: PageInfo!
}